export const sample = {
  items: [
    {
      description: 'Description. Very awesome item.',
      id: 2,
      location: null,
      pictures: {
        1: null,
        2: null,
        3: null,
      },
      price: 50,
      seller_id: 2,
      sold: false,
      title: 'Item 1',
      uri: 'http://localhost:5000/api/v1.0/user_items/2',
    },
    {
      description: 'Description 600',
      id: 3,
      location: null,
      pictures: {
        1: null,
        2: null,
        3: null,
      },
      price: 120,
      seller_id: 2,
      sold: false,
      title: 'New item 500',
      uri: 'http://localhost:5000/api/v1.0/user_items/3',
    },
    {
      description: 'LOl',
      id: 4,
      location: null,
      pictures: {
        1: null,
        2: null,
        3: null,
      },
      price: 200,
      seller_id: 2,
      sold: false,
      title: 'Jee',
      uri: 'http://localhost:5000/api/v1.0/user_items/4',
    },
    {
      description: 'Jees',
      id: 6,
      location: null,
      pictures: {
        1: null,
        2: null,
        3: null,
      },
      price: 100,
      seller_id: 2,
      sold: false,
      title: 'JEees Jeees',
      uri: 'http://localhost:5000/api/v1.0/user_items/6',
    },
    {
      description: 'Otoaeeontaonaoooenotaontaoenoteaoneoanoao',
      id: 7,
      location: null,
      pictures: {
        1: null,
        2: null,
        3: null,
      },
      price: 10200,
      seller_id: 2,
      sold: false,
      title: 'Neoa',
      uri: 'http://localhost:5000/api/v1.0/user_items/7',
    },
    {
      description: 'JEeeeeabaeoaneo',
      id: 8,
      location: null,
      pictures: {
        1: null,
        2: null,
        3: null,
      },
      price: 100,
      seller_id: 2,
      sold: false,
      title: 'Jees',
      uri: 'http://localhost:5000/api/v1.0/user_items/8',
    },
  ],
};
